### ISSUE TITLE
confirmation

### ISSUE THREAD

**Issue by coadler** [cdr/sail-aur#1]
@KSXGitHub

**Comment by KSXGitHub** [comment]
@coadler I have added you (`coadler`) to the list of Co-Maintainers (I did it on the website, I did not update the package itself). Is it safe for me to disown the package now? I'm not familiar with transferring AUR package ownership.

**Comment by coadler** [comment]
per https://wiki.archlinux.org/index.php/Arch_User_Repository (see `Maintaining packages` header) it sounds like it should transfer to me after a disown

**Comment by KSXGitHub** [comment]
@coadler Done.

**Comment by coadler** [comment]
Worked. Thanks :) 

Will email to discuss further details

**Comment by KSXGitHub** [comment]
BTW, you are not going to change PKGBULD into using `go` to build `code-server`, do you?

**Comment by KSXGitHub** [comment]
> Will email to discuss further details

If it is not private, let's just discuss them here. Managing inbox is a lot of work.

**Comment by coadler** [comment]
I plan to keep using the binary releases until compiles are <5-10s

**Comment by KSXGitHub** [comment]
> until compiles are <5-10s

only if you skip optimizations. :)
